runtime: python37
env: standard

handlers:
- url: /result
  script: auto

service: sentiment
instance_class: F4
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 10
  max_instances: 100